"""empty message

Revision ID: 854e4db25aec
Revises: 
Create Date: 2021-08-03 13:59:49.103852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854e4db25aec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('employee_name', sa.String(length=64), nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
